name: tag

on:
  push:
    tags:
    - 'v*'

permissions:
  packages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: versioning
      run: |
        echo "VERSION = \"${GITHUB_REF##*/v}\"" > pstyle/version.py
    - uses: wtnb75/actions/python@v1
      with:
        extra-args: "--extra drivers"
    - uses: wtnb75/actions/ruff@v1
    - uses: wtnb75/actions/pytest@v1
    - id: wheel
      uses: wtnb75/actions/wheel@v1
    - id: pdoc
      uses: wtnb75/actions/pdoc@v1
      with:
        output-dir: docs
        module: pstyle
        other-options: --docformat google
    - uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0
    - uses: wtnb75/actions/docker@v1
      with:
        push: 'true'
        context: .
        username: ${{ github.actor }}
        password: ${{ github.token }}
        image-version: ${{ github.ref_name }}
    - uses: wtnb75/actions/pypi-upload@v1
      with:
        username: ${{ secrets.TWINE_USERNAME }}
        password: ${{ secrets.TWINE_PASSWORD }}
        file: dist/${{ steps.wheel.outputs.filename }}
